#!/usr/bin/env bash
set -eu
prog=$(basename -- "$0")
exec docker run --env-file <(env -u PWD -u PATH -u TMPDIR) --workdir "$PWD" --volume /Users:/home --privileged=true --tmpfs /tmp --volume plashdata:/var/lib/plash -ti irae/docker-plash "$prog" "$@"
