#!/usr/bin/env bash
set -eu
prog=$(basename -- "$0")
envs=$(env -u PWD -u PATH -u TMPDIR)

# can an env be an command line option for echo?

exec docker run \
--env-file <(echo -n "$envs") \
--workdir "$PWD" \
--volume /Users:/home \
--privileged=true \
--tmpfs /tmp \
--volume plashdata:/var/lib/plash \
-ti irae/docker-plash "$prog" "$@"
